# Generated by Django 5.0.1 on 2024-01-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_rename_reciepent_transfer_reciever_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='reciever_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.CharField(default='298295', max_length=6, unique=True),
        ),
    ]
